apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
        - name: weatherapp
          image: gcr.io/------------project ID--------/weatherapp:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
