server:
  port: 8080

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=30m


weather:
  api:
    url: https://api.openweathermap.org/data/2.5/forecast
    key: 0492a5af263c26f2fbe504ee0fc5019f
